### PR TITLE
Feature/testing jwt

### PR DESCRIPTION
**Pull request by BryceHayden**
Check out the profile page and notice that the bug

### CODE REVIEW

**Review by zhutto — APPROVED** [review]
Score

**Comment by Romarioh39** [comment]
I like it.

**Review by spookyburger — APPROVED** [review]
Looks good

**Review by kchurch9 — APPROVED** [review]
Looks good

**Review by Romarioh39 — APPROVED** [review]
This looks great, Keep up the good work

**Review by Vishai — APPROVED** [review]
Stellar. Go Team Ramrod!

**Review by ghost — APPROVED** [review]
Looks better than good.

**Review by sgerber801 — APPROVED** [review]
What is for lunch?

**Review by hanisalam — APPROVED** [review]
cool

**Pull request merged**
